# Generated by Django 4.0.5 on 2022-06-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='Item',
        ),
    ]
