# Generated by Django 4.0.5 on 2022-06-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
