# Generated by Django 4.0.5 on 2022-06-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0003_alter_item_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
